language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t lmanyange/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lmanyange/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-af-south-1-403524832661"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY