language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t lmanyange/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lmanyange/docker-react npm run test